services:
  - type: web
    name: hive-protocol
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_PRIVY_APP_ID
        sync: false
      - key: NEXT_PUBLIC_MOCK_AUTH
        value: "false"
      - key: NEXT_PUBLIC_ALCHEMY_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ADMIN_ADDRESS
        sync: false
      - key: NEXT_PUBLIC_AUDIT_BOUNTY_ADDRESS
        sync: false
      - key: NEXT_PUBLIC_HIVE_INDEXER_URL
        value: "https://ce7529dc-5a0d-4505-8fca-655f68a298d1.squids.live/hive-indexer@v1/api/graphql"
      - key: NEXT_PUBLIC_HIVE_TREASURY_WALLET
        sync: false
      - key: NEXT_PUBLIC_HIVE_AGENTS_WALLET
        sync: false
      - key: NEXT_PUBLIC_HIVE_CREATORS_WALLET
        sync: false
      - key: NEXT_PUBLIC_HIVE_REFERRALS_WALLET
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: RPC_URL
        value: "https://sepolia.base.org"
      - key: X402_TREASURY_ADDRESS
        sync: false
      - key: BAGS_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
